import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

function syncCSSPlugin() {
  return {
    name: "sync-css",
    setup(build) {
      build.onEnd(() => {
        const out = "main.css";
        const target = "styles.css";
        try {
          if (fs.existsSync(out)) {
            fs.copyFileSync(out, target);
            console.log("Copied " + out + " → " + target);
          }
        } catch (e) {
          console.error("Failed to sync CSS:", e.message);
        }
      });
    },
  };
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [syncCSSPlugin()],
});

if (prod) {
  await context.rebuild();
  if (fs.existsSync("main.css")) {
    fs.renameSync("main.css", "styles.css");
  }
  process.exit(0);
} else {
  await context.watch();
}
